### ISSUE TITLE
Brand new pull causes errors

### ISSUE THREAD

**Issue by rfcohen** [carolzhou/multiPhATE2#12]
Love the tool.  However, I've been successful using multiphate 1 and 2 and today I saw there were updates that I didn't have.  So I did 'git pull'.  Reran the database set up and then tried to just run the sample.  And I get this output:

`(multiphate) rcohen@APTint:~/multiPhATE2$ python3 multiPhate.py sample.multiPhate.config 
sh: 1: cannot create /vog.gene.headers.lst: Permission denied
sh: 1: cannot create /vog.protein.headers.lst: Permission denied
multiPhate says, ERROR: unrecognized line in config file:  
multiPhate says, User input has been checked.
  If you are satisfied that your databases are correctly configured,
  set check_databases to 'false' in your configuration file,
  and proceed with multiPhATE processing. Exiting now.
`

I don't understand why it's trying to create files at the root?  Further, I'm using the sample config straight from GitHub so how is there an error in the config file?

Thank you.

**Comment by carolzhou** [comment]
Hi Rob,

Please check your configuration file to verify that the fullpath/filename
of your VOG Gene and VOG Protein databases are correct. The code is trying
to extract fasta headers from those databases and write them to the
Databases/VOGs/ directory. It doesn't seem like file permissions should be
the problem, since you (as the program user) should have permission to
write to any directory within your multiPhATE2 installation. However,
better check that to be sure. Please post or send me your configuration
file, as that might prove helpful.

Also, please be aware that mutliPhATE2 is currently in peer review and I am
modifying/updating the code every few days. The 2.0 release should be ready
by the end of January, but until then the code will be in flux, and I
cannot guarantee that all the glitches and typos will be worked out until I
do the full integration testing. So please keep that in mind.

-Carol

**Comment by rfcohen** [comment]
Hi Carol and thanks for writing back so quickly.

I’m using the sample.multiphate.config file.  Just trying to make it run cleanly first.

The file is attached straight from GitHub.

It seems like the problem is here in multiphate.py:

        PHATE_VOG_GENE_BASE_DIR = os.path.dirname(match_vogGeneDBpath.group(1)) + '/'

Which does some gyrations but its source is the config file.

p_vogGeneDBpath               = re.compile("vog_gene_database_path='(.*)’")

If this is blank in the config file, the BASE_DIR is blank + “/“ which shows up as the root.

Hope this helps.  I look forward to using this, it’s really good.

-Rob

**Comment by carolzhou** [comment]
Hi Rob,  You cannot use the sample config file straight out of the box. You
need to specify the complete path/filenames for the databases you are
using.  Please try again and see if that fixes the problem.  -Carol
