### ISSUE TITLE
Functional Annotation Only

### ISSUE THREAD

**Issue by rfcohen** [carolzhou/multiPhATE2#16]
We're doing great with MultiPhate and it's working nicely.  I see that there's the opportunity to experiment with multiple different gene callers and then pick the one you like the best.  Is there a way to pause the process after gene calling, or perhaps inject another application that combines the gene calls or allows for some hand tuning of the gene calls and then use that as the input to functional annotation?

Thanks again.  Nice tool.

**Comment by rfcohen** [comment]
I think the answer is never mind.  Look at checkpointing.

**Comment by rfcohen** [comment]
Despite thinking I knew the answer, I still have a question.  What are the input file(s) to the functional annotation step?

**Comment by carolzhou** [comment]
In regards to your first question, you can halt computations after gene finding simply by setting translate_only to 'true'.  MultiPhATE2 does combine the different gene callers. You can select any of 3 gene-call sets:  superset, consensus, or common core. The README and the wiki explain more what these are. Also, you can look at the CGC_results.txt file (import into Excel to view) to examine the gene calls side-by-side to help you decide what you like. If you want to create your own gene-call set (custom), then you can use Genbank calls, or RAST, or construct your own curated calls and put them in the PipelineIntput/ folder. Just be sure to format them exactly like the gff that Prodigal produces (see Eb_P2.custom.fasta example in PipelineInput/). In order to re-start computations at the PhATE annotation engine level, you need to have run the gene finding module (now set translate_only to 'false') because you need the files in the right places. So, the input files to the functional annotation step are the output files from multiPhATE2 gene calling. Well, you don't necessarily need all of them. You could run all the gene callers, then re-start with the gene call set that you like (setting that set as primary_calls=''), and then set the phate checkpoint so that computations restart at that point and use your preferred gene-call set as the input. Take a look at the wiki to follow one or more use cases.  Let me know if you need more help.

**Comment by carolzhou** [comment]
Correction: the name of the sample custom gene-call set is:  Eb_P2.custom.gff.

**Comment by carolzhou** [comment]
I'm closing this issue. Let me know if you have additional issues running the code. Thank you for using multiPhATE2!
