### ISSUE TITLE
Python syntax bug?

### ISSUE THREAD

**Issue by iddoweiner** [carolzhou/multiPhATE2#21]
Thanks for this cool tool.
Followed the instructions on readme (built conda env, copied input to PipelineInput, created a config file), then ran this command:
```
python3 multiPhate.py myInput.multiPhate.config
```
I get an "invalid syntax error". Could this be caused due to installation / input? Has this ever happened to you?
```
  File "multiPhate.py", line 2390
    print(f'multiPhate says, Running {jsonFile} on PID {os.getpid()}')
                                                                    ^
SyntaxError: invalid syntax
```
p.s.
I get the same error when running with the exmaple config file: "sample.multiPhate.config"

**Comment by carolzhou** [comment]
I get this error when running multiPhATE2 under Python 2.x.  Please double check whether your Conda environment is running Python 3.x and is activated.

**Comment by iddoweiner** [comment]
thx for getting back to me.
I suspected that too, but it looks ok:
```
(multiphate2) me@server:~/multiPhATE2$ python --version
Python 3.7.9
```

**Comment by carolzhou** [comment]
Let's try this:  Edit multiPhate.py by commenting out the line, print(f'multiPhate says, .... (line 2390).  Let's see if the code fails at the next print statement.

**Comment by carolzhou** [comment]
Try no. 2:  Remove the first line in the multiPhate.py file:  #!/usr/bin/env python.  Let me know if that makes a difference on your system.

**Comment by carolzhou** [comment]
The syntax error is reproducible when running multiPhATE2 under Python 2.x; multiPhATE2 requires Python 3.x.  The #!/usr/bin/env python at the top of a code file assures that the version of python occurring first in your search PATH is used, although I believe this should be overridden by Conda, or overridden by invoking multiPhATE2 with python3, in any case. So, I don't know what is causing this issue for you. Please try one of the above fixes and let me know if it works, so that I will know how to fix this for other users, if the issue arises again. Thank you for using multiPhATE2.
