### ISSUE TITLE
Regarding phate_sequenceAnnotation_main.out results

### ISSUE THREAD

**Issue by ShailNair** [carolzhou/multiPhATE2#4]
HI,
So, my phate_sequenceAnnotation_main.out have two sections 1) the called genes with annotated the blast results. (2)Translated protein and their blast output. But, I see that most of the annotated genes are linked to some specific function but in translated protein, they are assigned as hypothetical protein. In fact, at the gene level, almost 80% of the called genes are assigned to some functions but at the protein level, most of them are shown as hypothetical protein. 
While some of the genes which are assigned as hypothetical protein, at protein level have function (very few though).

**Comment by carolzhou** [comment]
What databases did you run against?

**Comment by ShailNair** [comment]
I had called for all databases except Phmmer and jackhammer

ncbiVirusGenomeBlast is True
   ncbiVirusProteinBlast is True
   refseqProteinBlast is True
   refseqGeneBlast is False
   pvogsBlast is True
   vogGeneBlast is True
   vogProteinBlast is True
   phantomeBlast is True
   phageEnzymeBlast is False
   keggVirusBlast is False
   pfamBlast is False
   smartBlast is False
   swissprotBlast is True
   uniprotBlast is False
   nrBlast is True
   cazyBlast is True
   hmmscan is True
   ncbiVirusGenomeHmm is False
   ncbiVirusProteinHmm is False
   refseqProteinHmm is False
   refseqGeneHmm is False
   pvogsHmm is True
   vogsHmm is True

From the _sequenceAnnotation_main.out file I see source as VOGs for genes and pVOGhmms and VOGhmms for proteins. here is the output file

[phate_sequenceAnnotation_main.out.txt](https://github.com/carolzhou/multiPhATE2/files/5419357/phate_sequenceAnnotation_main.out.txt)

**Comment by carolzhou** [comment]
The results you are seeing from doing blast and hmm searches against databases is exactly what one would expect. Many of the hits are to "hypothetical" genes, which are not yet well annotated. For any given gene or protein, you will want to look at the results from several database searches. Typically you will see a mix of results in which some hits are well annotated and others are not, and sometimes a gene/protein will be only "hypothetical". Because you are using the gene-call superset, you are including gene calls from Phanotate, which tends to predict more genes than do other callers. Some of the genes predicted by Phanotate may not have annotations at all. This is because Phanotate may detect genes not detected by other callers, and for which there may be little or no precedent in the databases.
What concerns me more is that you are not seeing results from several of the databases you selected. I see results from NCBI Virus Genome, VOG gene, pVOGs, and VOG hmm.  I do not see results from NCBI Virus Protein, Refseq Protein, Phantome, Swissprot, NR, or CAZy.  As for CAZy, typically there are only a few hits in a phage genome, as this data set is limited to carbohydrate enzymes, so it is possible to have not hits at all in a genome. But for the other databases, I would expect hits. Did the code return any error messages when trying to search against these databases?

**Comment by ShailNair** [comment]
Hi,
No. The pipeline was successfully executed. the terminal output says blast completed for all mentioned database. I thought maybe the pipeline auto-selects the most preferred annotated genes/proteins (based on high similarity) and hence, results form a few databases, even though it searched all databases. :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes:
logs:
[pipeline_terminal_output.txt](https://github.com/carolzhou/multiPhATE2/files/5426622/pipeline_terminal_output.txt)
[phate_sequenceAnnotation_main.log](https://github.com/carolzhou/multiPhATE2/files/5426627/phate_sequenceAnnotation_main.log)

**Comment by carolzhou** [comment]
I ran multiPhATE with your genome and one of my own, and discovered that
your sequences have rather few or no hits per database until the blast
homology cutoff is set quite low. Your genome must be relatively unique
compared to what is in the databases and compared to the 30+ test genomes I
have run through the code so far.

I suggest that you start by setting the blastp cutoff to 30% and see what
you get. But blast hits at that low level of similarity will not be
reliable, so be sure to consider the strength of a hit.

**Comment by ShailNair** [comment]
Yea. it is a novel phage. Thanks for the check-up and suggestions. I will try with low threshold.

**Comment by carolzhou** [comment]
Great! Let me know if you encounter any other issues.

**Comment by carolzhou** [comment]
Ok, I will run your genome through multiPhATE2 on my computer, though I will skip NR, and see what happens.On Oct 22, 2020, at 5:43 PM, Shail <notifications@github.com> wrote:Hi,
N0. The pipeline was successfully executed. the terminal output says blast completed for all mentioned database.
logs:
pipeline_terminal_output.txt
phate_sequenceAnnotation_main.log—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ShailNair** [comment]
@carolzhou you said to reduce the blastp cutoff,  it is the blastp identity command in the config file (which is currently blastp_identity='90'). isn't it?

**Comment by carolzhou** [comment]
That's right. I got plenty of hits on your genome when I reduced the
blastp_identity to 30.

**Comment by ShailNair** [comment]
Thanks for the analysis and suggestions. But if we reduce the threshold to such a low degree wouldn't it include more false annotations? Because many of the genes are homologous to each other (with varying degrees). Even though it is a novel phage, Isn't it dubious to have such a high degree of unknown genes (with default BLASP settings)?

(PS: My point isn't to raise questions or doubts about the pipeline or your answers. I am relatively new to genomics, especially to phage genomics. Just want to learn more from whoever and from wherever possible. :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes:)

**Comment by carolzhou** [comment]
Absulutely. Lowering the stringency will generate hits that are not
reliable in terms of transferring function. The lower limit for detecting
any meaningful homology at the protein level is about 30%. That is because
protein structure is conserved down to about that level. But in terms of
reliable functional annotation, a good working cutoff would be around 60%
with good coverage, perhaps covering most of the sequence. That is all up
to your interpretation. If there are particular genes of interest, I
suggest that you run multiphate against one of the databases that yields
vog groupings, and then input the fasta group into downstream analysis
programs, such as alignments (eg, clustalO).

**Comment by ShailNair** [comment]
Thanks. that's very clear. i will run the pipeline with 30% threshold and then can check with other analyses. Thanks.
